services:
  - type: web
    name: mundial
    env: java
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/mundial-1.jar
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: "mongodb+srv://rauldiaz0530_db_user:Raul0530@cluster0.7pycc8p.mongodb.net/mundial"
      - key: SPRING_DATA_MONGODB_DATABASE
        value: "mundial"
      - key: SERVER_PORT
        value: "10000"